<?php
	include('data/constants.php');
	require_once('init/model.php');
	require_once('init/view.php');
	require_once('init/controller.php');
	require_once('init/route.php');
	require_once('init/db_init.php');
	require_once('init/share.php');
	Dbase::reset();
	Route::start();
